#
# Copyright 2018 Ettus Research, A National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# RFNoC Utility Sources
##################################################
RFNOC_UTIL_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/erfnoc/utils/, \
context_handler_sync.v \
ctrlport_timer.v \
))