#
# Copyright 2014 Ettus Research LLC
#

##################################################
# radio library
##################################################
RADIO_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/radio/, \
radio_core.v \
radio_core_regs.vh \
db_control.v \
rx_frontend_gen3.v \
tx_frontend_gen3.v \
rx_control_gen3.v \
tx_control_gen3.v \
noc_block_radio_core.v \
))

RADIO_LEGACY_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/radio/, \
./radio_legacy.v \
))
