#
# Copyright 2014 Ettus Research LLC
#

##################################################
# RFNoC Sources
##################################################
RFNOC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/, \
noc_shell.v \
simple_axi_wrapper.v \
null_source.v \
noc_block_axi_fifo_loopback.v \
noc_block_fir_filter.v \
noc_block_null_source.v \
))
