#
# Copyright 2014 Ettus Research LLC
#

##################################################
# radio library
##################################################
RADIO_200_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/radio_200/, \
./radio_legacy.v \
))
