onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/ce_clk
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/ce_rst
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/symbol_i
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/symbol_q
add wave -noupdate -divider {RFNoC Block OFDM Constellation Demapper}
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/i_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/i_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/i_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/i_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/o_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/o_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/o_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/o_tvalid
add wave -noupdate -divider {OFDM Constellation Demapper}
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/i_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/i_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/i_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/i_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/modulation_order
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/punctured_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/punctured_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/punctured_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/punctured_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaling_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaling_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaling_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaling_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaled_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaled_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaled_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/scaled_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/rounded_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/rounded_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/rounded_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/rounded_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/bit_cnt
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/bits_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/bits_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/bits_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/bits_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/packed_bits
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/packed_bits_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/packed_bits_tvalid
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/o_tdata
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/o_tlast
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/o_tready
add wave -noupdate /noc_block_ofdm_constellation_demapper_tb/noc_block_ofdm_constellation_demapper/ofdm_constellation_demapper/o_tvalid
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {96600000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 265
configure wave -valuecolwidth 219
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {91265786 ps} {122508327 ps}
