######################################################################
#
# File name : noc_block_constant_tb_wave.do
# Created on: Thu Apr 21 18:03:12 PDT 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
