onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/NOC_ID
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/STR_SINK_FIFOSIZE
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/SR_NEXT_DST
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/SR_AXI_CONFIG
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/SR_SUM_LEN
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/SR_DIVISOR
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/SR_READBACK
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/bus_clk
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/bus_rst
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/ce_clk
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/ce_rst
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/i_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/i_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/i_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/i_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/o_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/o_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/o_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/o_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/debug
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/next_dst
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/rb_addr
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/sum_len
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/sum_len_changed
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/divisor
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/set_data
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/set_addr
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/set_stb
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/clear_tx_seqnum
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_sink_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_src_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_sink_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_sink_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_sink_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_src_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_src_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/str_src_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/m_axis_data_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/s_axis_data_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/m_axis_data_tuser
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/m_axis_data_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/m_axis_data_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/m_axis_data_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/s_axis_data_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/s_axis_data_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/s_axis_data_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/ipart_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/ipart_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/ipart_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/ipart_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qpart_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qpart_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qpart_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qpart_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/isum_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/isum_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/isum_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/isum_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qsum_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qsum_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qsum_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qsum_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/iavg_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/iavg_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/iavg_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/iavg_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/idivisor_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/idividend_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qavg_tdata
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qavg_tlast
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qavg_tvalid
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qavg_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qdivisor_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/qdividend_tready
add wave -noupdate /noc_block_moving_avg_tb/noc_block_moving_avg/rb_data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {978445 ps} {1001135 ps}
set StdArithNoWarnings 1
set NumericStdNoWarnings 1
