#
# Copyright 2014 Ettus Research LLC
#

##################################################
# Coregen Sources
##################################################
LIBCOREGEN_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/coregen/, \
simple_fir.v \
simple_fir.xco \
))


#decim_4_5.v \
#decim_4_5.xco \
