#
# LTE/JESD204 Clocking sources
#
set_property IOSTANDARD LVDS_25 [get_ports codec_loop_clk_out_*]
set_property PACKAGE_PIN V13 [get_ports codec_loop_clk_out_p]
set_property PACKAGE_PIN V14 [get_ports codec_loop_clk_out_n]
set_property PACKAGE_PIN F10 [get_ports codec_loop_clk_in_p]
set_property PACKAGE_PIN E10 [get_ports codec_loop_clk_in_n]
#
# Power Amp Interface (JESD204+supporting signalling)
#
set_property IOSTANDARD LVDS_25 [get_ports RD1_ET_SYNCp]
set_property IOSTANDARD LVDS_25 [get_ports RD1_ET_SYNCn]
set_property IOSTANDARD LVDS_25 [get_ports RD1_ET_FRAME_CLKp]
set_property IOSTANDARD LVDS_25 [get_ports RD1_ET_FRAME_CLKn]
set_property PACKAGE_PIN B17 [get_ports RD1_ET_SYNCp]
set_property PACKAGE_PIN B18 [get_ports RD1_ET_SYNCn]
set_property PACKAGE_PIN D17 [get_ports RD1_ET_FRAME_CLKp]
set_property PACKAGE_PIN C17 [get_ports RD1_ET_FRAME_CLKn]
set_property PACKAGE_PIN D7 [get_ports RD1_ET_ENV0p]
set_property PACKAGE_PIN C7 [get_ports RD1_ET_ENV0n]

set_property IOSTANDARD LVDS_25 [get_ports RD2_ET_SYNCp]
set_property IOSTANDARD LVDS_25 [get_ports RD2_ET_SYNCn]
set_property IOSTANDARD LVDS_25 [get_ports RD2_ET_FRAME_CLKp]
set_property IOSTANDARD LVDS_25 [get_ports RD2_ET_FRAME_CLKn]
set_property PACKAGE_PIN E19 [get_ports RD2_ET_SYNCp]
set_property PACKAGE_PIN D19 [get_ports RD2_ET_SYNCn]
set_property PACKAGE_PIN C18 [get_ports RD2_ET_FRAME_CLKp]
set_property PACKAGE_PIN C19 [get_ports RD2_ET_FRAME_CLKn]
set_property PACKAGE_PIN B6 [get_ports RD2_ET_ENV0p]
set_property PACKAGE_PIN A6 [get_ports RD2_ET_ENV0n]

set_property PACKAGE_PIN F4 [get_ports RD1_RX_TX_LOOPBACK]
set_property PACKAGE_PIN L6 [get_ports RD1_TEMP_SDA]
set_property PACKAGE_PIN A1 [get_ports RD1_TEMP_SCL]
set_property PACKAGE_PIN B1 [get_ports RD1_RFPWR_CONV]
set_property PACKAGE_PIN B2 [get_ports RD1_RFPWR_SDO]
set_property PACKAGE_PIN C2 [get_ports RD1_RFPWR_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RD1_RX_TX_LOOPBACK]
set_property IOSTANDARD LVCMOS33 [get_ports RD1_TEMP_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports RD1_TEMP_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports RD1_RFPWR_CONV]
set_property IOSTANDARD LVCMOS33 [get_ports RD1_RFPWR_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports RD1_RFPWR_SCLK]
set_property PACKAGE_PIN T3 [get_ports RD1_ET_SPI_SCLK]
set_property PACKAGE_PIN U7 [get_ports RD1_ET_SPI_SDIN]
set_property PACKAGE_PIN U1 [get_ports RD1_ET_SPI_SDOUT]
set_property PACKAGE_PIN T1 [get_ports RD1_ET_SPI_SDEN]
set_property PACKAGE_PIN V2 [get_ports RD1_ET_RESET]
set_property PACKAGE_PIN U2 [get_ports RD1_ET_ALARM]
set_property PACKAGE_PIN R2 [get_ports RD1_ET_WARNING]
set_property PACKAGE_PIN R3 [get_ports RD1_SLEEP]
set_property PACKAGE_PIN Y2 [get_ports RD1_P_READY]
set_property PACKAGE_PIN W2 [get_ports RD1_ICSP_CLK]
set_property PACKAGE_PIN Y1 [get_ports RD1_ICSP_DAT]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_SPI_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_SPI_SDIN]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_SPI_SDOUT]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_SPI_SDEN]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_ALARM]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ET_WARNING]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_SLEEP]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_P_READY]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ICSP_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports RD1_ICSP_DAT]


set_property PACKAGE_PIN D1 [get_ports RD2_RX_TX_LOOPBACK]
set_property PACKAGE_PIN E1 [get_ports RD2_TEMP_SDA]
set_property PACKAGE_PIN D2 [get_ports RD2_TEMP_SCL]
set_property PACKAGE_PIN E2 [get_ports RD2_RFPWR_CONV]
set_property PACKAGE_PIN F1 [get_ports RD2_RFPWR_SDO]
set_property PACKAGE_PIN G1 [get_ports RD2_RFPWR_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RD2_RX_TX_LOOPBACK]
set_property IOSTANDARD LVCMOS33 [get_ports RD2_TEMP_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports RD2_TEMP_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports RD2_RFPWR_CONV]
set_property IOSTANDARD LVCMOS33 [get_ports RD2_RFPWR_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports RD2_RFPWR_SCLK]
set_property PACKAGE_PIN W1 [get_ports RD2_ET_SPI_SCLK]
set_property PACKAGE_PIN V3 [get_ports RD2_ET_SPI_SDIN]
set_property PACKAGE_PIN U3 [get_ports RD2_ET_SPI_SDOUT]
set_property PACKAGE_PIN AB1 [get_ports RD2_ET_SPI_SDEN]
set_property PACKAGE_PIN AA1 [get_ports RD2_ET_RESET]
set_property PACKAGE_PIN AB2 [get_ports RD2_ET_ALARM]
set_property PACKAGE_PIN AB3 [get_ports RD2_ET_WARNING]
set_property PACKAGE_PIN AA3 [get_ports RD2_SLEEP]
set_property PACKAGE_PIN Y3 [get_ports RD2_P_READY]
set_property PACKAGE_PIN AB5 [get_ports RD2_ICSP_CLK]
set_property PACKAGE_PIN AA5 [get_ports RD2_ICSP_DAT]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_SPI_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_SPI_SDIN]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_SPI_SDOUT]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_SPI_SDEN]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_ALARM]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ET_WARNING]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_SLEEP]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_P_READY]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ICSP_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports RD2_ICSP_DAT]
