#
# Copyright 2012-2013 Ettus Research LLC
#

##################################################
# FIFO 200 Sources
##################################################
FIFO_200_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/fifo_200/, \
axi_fifo_legacy.v \
))
