#
# Copyright 2015 Ettus Research LLC
#

##################################################
# Simulation Libraries/Headers for AXI based interfaces
##################################################
SIM_RFNOC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../sim/rfnoc/, \
sim_rfnoc_lib.svh \
))
