#
# Copyright 2018 Ettus Research, A National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# RFNoC Utility Sources
##################################################
RFNOC_BLOCK_NULL_SRC_SINK_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_null_src_sink/, \
rfnoc_block_null_src_sink.v \
))
