#
# Copyright 2013 Ettus Research LLC
# Copyright 2016 Ettus Research, a National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# VITA Sources
##################################################
VITA_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/vita/, \
flow_control_responder.v \
packet_error_responder.v \
))
