######################################################################
#
# File name : noc_block_siggen_tb_wave.do
# Created on: Wed Apr 06 17:10:32 PDT 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
